#!/usr/bin/env python3
"""Generate per-tool agent configuration from the neutral sources in agent/.

Sources (the only files to edit):
    agent/skills/<name>/SKILL.md  -> .opencode/skills/, .claude/skills/, .agents/skills/
    agent/mcp.json                -> opencode.json, .mcp.json, .codex/config.toml
    agent/hooks.json              -> .claude/settings.json, .codex/hooks.json

Usage:
    uv run python scripts/sync_agent_config.py          # generate
    uv run python scripts/sync_agent_config.py --check  # exit 1 on drift (CI)
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AGENT_DIR = ROOT / "agent"
SKILLS_SOURCE = AGENT_DIR / "skills"
MCP_SOURCE = AGENT_DIR / "mcp.json"
HOOKS_SOURCE = AGENT_DIR / "hooks.json"
SKILL_MIRRORS = (
    ROOT / ".opencode" / "skills",
    ROOT / ".claude" / "skills",
    ROOT / ".agents" / "skills",
)
LEGACY_PATHS = (ROOT / ".opencode" / "opencode.json",)
SKILL_FILE = "SKILL.md"
OPENCODE_PLUGIN = ".opencode/plugins/graphify.js"
GENERATED_HEADER = (
    "Generated by scripts/sync_agent_config.py from agent/ — edit the source, not this file."
)


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT))


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def dumps(data: object) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def toml_string(value: str) -> str:
    return json.dumps(value)


def skill_sources() -> dict[str, str]:
    skills: dict[str, str] = {}
    if SKILLS_SOURCE.is_dir():
        for child in sorted(SKILLS_SOURCE.iterdir()):
            skill_file = child / SKILL_FILE
            if skill_file.is_file():
                skills[child.name] = skill_file.read_text()
    return skills


def opencode_config(servers: dict) -> str:
    mcp = {}
    for name, server in servers.items():
        entry: dict = {
            "type": "local",
            "command": [server["command"], *server.get("args", [])],
            "enabled": True,
        }
        if server.get("env"):
            entry["environment"] = server["env"]
        mcp[name] = entry
    return dumps(
        {
            "$schema": "https://opencode.ai/config.json",
            "instructions": ["AGENTS.md"],
            "plugin": [OPENCODE_PLUGIN],
            "mcp": mcp,
        }
    )


def claude_mcp_config(servers: dict) -> str:
    mcp = {}
    for name, server in servers.items():
        entry: dict = {"command": server["command"], "args": server.get("args", [])}
        if server.get("env"):
            entry["env"] = server["env"]
        mcp[name] = entry
    return dumps({"mcpServers": mcp})


def codex_config(servers: dict) -> str:
    lines = [f"# {GENERATED_HEADER}", ""]
    for name in sorted(servers):
        server = servers[name]
        lines.append(f"[mcp_servers.{name}]")
        lines.append(f"command = {toml_string(server['command'])}")
        args = ", ".join(toml_string(arg) for arg in server.get("args", []))
        lines.append(f"args = [{args}]")
        lines.append("")
        if server.get("env"):
            lines.append(f"[mcp_servers.{name}.env]")
            for key in sorted(server["env"]):
                lines.append(f"{key} = {toml_string(server['env'][key])}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def claude_settings(hooks: dict) -> str:
    session_start = hooks["session_start"]
    command = f'python3 "$CLAUDE_PROJECT_DIR/{session_start["script"]}"'
    return dumps(
        {
            "hooks": {
                "SessionStart": [
                    {
                        "matcher": session_start["matcher"],
                        "hooks": [{"type": "command", "command": command}],
                    }
                ]
            }
        }
    )


def codex_hooks(hooks: dict) -> str:
    session_start = hooks["session_start"]
    command = f'python3 "$(git rev-parse --show-toplevel)/{session_start["script"]}" --format codex'
    return dumps(
        {
            "description": GENERATED_HEADER,
            "hooks": {
                "SessionStart": [
                    {
                        "matcher": session_start["matcher"],
                        "hooks": [
                            {
                                "type": "command",
                                "command": command,
                                "statusMessage": "Loading knowledge graph hint",
                                "additionalContextLimit": 1000,
                            }
                        ],
                    }
                ]
            },
        }
    )


def build_outputs() -> dict[Path, str]:
    servers = load_json(MCP_SOURCE)["servers"]
    hooks = load_json(HOOKS_SOURCE)
    outputs: dict[Path, str] = {}
    for mirror in SKILL_MIRRORS:
        for name, text in skill_sources().items():
            outputs[mirror / name / SKILL_FILE] = text
    outputs[ROOT / "opencode.json"] = opencode_config(servers)
    outputs[ROOT / ".mcp.json"] = claude_mcp_config(servers)
    outputs[ROOT / ".codex" / "config.toml"] = codex_config(servers)
    outputs[ROOT / ".claude" / "settings.json"] = claude_settings(hooks)
    outputs[ROOT / ".codex" / "hooks.json"] = codex_hooks(hooks)
    return outputs


def sync(check: bool) -> int:
    if not SKILLS_SOURCE.is_dir():
        print(f"error: no skills found under {SKILLS_SOURCE}", file=sys.stderr)
        return 1

    outputs = build_outputs()
    stale: list[str] = []

    for path, text in outputs.items():
        current = path.read_text() if path.is_file() else None
        if current == text:
            continue
        stale.append(rel(path))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)

    expected_skills = set(skill_sources())
    for mirror in SKILL_MIRRORS:
        if not mirror.is_dir():
            continue
        for child in sorted(mirror.iterdir()):
            if child.is_dir() and child.name not in expected_skills:
                stale.append(f"{rel(child)} (orphan)")
                if not check:
                    shutil.rmtree(child)

    for path in LEGACY_PATHS:
        if path.exists():
            stale.append(f"{rel(path)} (legacy)")
            if not check:
                path.unlink()

    if check and stale:
        print("Agent files are stale relative to agent/ sources:")
        for path in stale:
            print(f"  {path}")
        print("Run: uv run python scripts/sync_agent_config.py")
        return 1

    action = "checked" if check else "generated"
    print(f"{action} {len(outputs)} file(s) from agent/ sources")
    if not check and stale:
        print("updated:")
        for path in stale:
            print(f"  {path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify without writing")
    args = parser.parse_args()
    return sync(check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
